"""Added relationships and tablenames

Revision ID: 039e534a2a13
Revises: 
Create Date: 2025-07-13 11:03:28.206494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '039e534a2a13'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('transaction_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'stk_push_response', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('transaction_user_id_fkey'), 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
