"""empty message

Revision ID: 3eb7ce950929
Revises: 960c212e3f8a
Create Date: 2025-07-24 13:43:35.089746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3eb7ce950929'
down_revision = '960c212e3f8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stk_push_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Phone_number', sa.String(length=20), nullable=False))
        batch_op.alter_column('business_shortcode',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('stk_push_request_checkout_request_id_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('stk_push_request_merchant_request_id_key'), type_='unique')
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stk_push_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint(batch_op.f('stk_push_request_merchant_request_id_key'), ['merchant_request_id'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('stk_push_request_checkout_request_id_key'), ['checkout_request_id'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('business_shortcode',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('Phone_number')

    # ### end Alembic commands ###
