"""empty message

Revision ID: 658fc0c68512
Revises: 039e534a2a13
Create Date: 2025-07-22 01:05:28.924095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '658fc0c68512'
down_revision = '039e534a2a13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('response_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('transaction_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'stk_push_response', ['response_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('transaction_user_id_fkey'), 'stk_push_response', ['user_id'], ['id'])
        batch_op.drop_column('response_id')

    # ### end Alembic commands ###
