"""empty message

Revision ID: 960c212e3f8a
Revises: bb347bf9d94f
Create Date: 2025-07-22 15:40:53.398742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '960c212e3f8a'
down_revision = 'bb347bf9d94f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stk_push_request', schema=None) as batch_op:
        batch_op.alter_column('business_shortcode',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stk_push_request', schema=None) as batch_op:
        batch_op.alter_column('business_shortcode',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###
