"""empty message

Revision ID: b021edafef47
Revises: 3eb7ce950929
Create Date: 2025-07-24 14:01:43.290602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b021edafef47'
down_revision = '3eb7ce950929'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stk_push_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=False))
        batch_op.drop_column('Phone_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stk_push_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
