"""empty message

Revision ID: f36a766831fa
Revises: b021edafef47
Create Date: 2025-07-28 15:59:51.548037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f36a766831fa'
down_revision = 'b021edafef47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('response_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('transaction_request_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'stk_push_response', ['response_id'], ['id'])
        batch_op.drop_column('request_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('transaction_request_id_fkey'), 'stk_push_request', ['request_id'], ['id'])
        batch_op.drop_column('response_id')

    # ### end Alembic commands ###
